### PR TITLE
midproject

### PR DESCRIPTION
**Pull request by ydDianYu**
Progress:
- [Code](https://github.com/MSIA/2021-msia423-yu-dian-project/blob/develop/src/s3.py) that uploads raw data into a configurable S3 bucket;
- [Code](https://github.com/MSIA/2021-msia423-yu-dian-project/blob/develop/src/add_tweets.py) that creates database schema locally in SQLite or RDS based on a configuration;
- [Dockerfile](https://github.com/MSIA/2021-msia423-yu-dian-project/blob/develop/Dockerfile) that defines a Docker image that runs the steps above via two separate `docker run` commands;
- [README.md](https://github.com/MSIA/2021-msia423-yu-dian-project/blob/develop/README.md) that contains instructions to build and run the Docker image and container.

To QA partner @hanyucai 
- Please test the functionalities of the [s3.py](https://github.com/MSIA/2021-msia423-yu-dian-project/blob/develop/src/s3.py) and [add_tweets.py](https://github.com/MSIA/2021-msia423-yu-dian-project/blob/develop/src/add_tweets.py) scripts to make sure that you are able to upload data to S3 and to create the database schema locally. To do this, you will need to use the [Dockerfile](https://github.com/MSIA/2021-msia423-yu-dian-project/blob/develop/Dockerfile) to create a Docker image. More instructions are included in [README.md](https://github.com/MSIA/2021-msia423-yu-dian-project/blob/develop/README.md).
- Besides functionalities, it would be great if you could provide feedback on readability, design, testing, and documentation.

### CODE REVIEW

**Comment by hanyucai** [comment]
This comment is for the "Dockerfile".
I noticed that you place the Dockerfile at the root repository, and I can successfully initiate the docker image by running this Dockefile! The format and coding for this Dockerfile is correct. However, I also noticed that there is a second Dockerfile inside the app folder and you may consider removing this second Dockerfile if you don't plan to use it.

**Comment by hanyucai** [comment]
This comment is for the "run.py".
I'm able to upload the raw data to my s3 backet using this "run.py", the file works well in terms of functionality! 
From line 17-27, you named the sub parser by "sb_xxx", but for line 31, you named it by "sp_xxx". Since those parsers have similar functionality, I guess you might make a typo for naming here.

**Comment by ydDianYu** [comment]
> This comment is for the "Dockerfile".
> I noticed that you place the Dockerfile at the root repository, and I can successfully initiate the docker image by running this Dockefile! The format and coding for this Dockerfile is correct. However, I also noticed that there is a second Dockerfile inside the app folder and you may consider removing this second Dockerfile if you don't plan to use it.

Thanks for the comment! And yes, I think the Dockerfile in the app folder could be redundant as you pointed out. I will make a new commit to remove it before merging the pull request.

**Comment by ydDianYu** [comment]
> This comment is for the "run.py".
> I'm able to upload the raw data to my s3 backet using this "run.py", the file works well in terms of functionality! It's really nice to have an "else: parser.print_help()" at line 38 so it will print the helper messages if user doesn't choose an option.
> One problem about formatting is that there are a mix of double quotes and single quotes, and it might be better to choose one type of quotes and stick with it for the overall script.
> 
> This comment is for the "add_tweets.py".
> You may consider add a class like "tweet_manager" and functions like "add_newtweets" to enable users add new tweets to the database. The detailed references for the "tweet_manager" can be found at the project sample template https://github.com/MSIA/2021-msia423-template-repository/blob/main/src/add_songs.py .

I'll definitely turn the double quotes into single quotes in the run.py file. Thanks for pointing that out!

Also, as you suggested, I did actually write a `TweetManager` class and a corresponding `add_newtweets` function in the beginning. However, I ended up removing them because I don't think my app will require users to add new tweets to the database. According to my plans, I would only use the database to store preprocessed data for training purposes. When using the web app, the user would indeed enter a tweet, but it would go directly into a pre-trained model instead of the database. Thus, I think it would be unnecessary to enable users to add new rows to the database. Thanks so much for the suggestion though! I think it is very thoughtful.

**Comment by hanyucai** [comment]
The Overall functionality and Design are great! I tested the codes following the guidelines on README.MD, the guidelines are pretty clear and easy to follow with. I love the idea that you placed a screen sheet of Trump's tweet on the top of README.MD, which adds more fun for the project.

**Comment by hanyucai** [comment]
The above are my reviews for each scripts, including my findings of some minor issues. You could fix those issues following my guidelines above.
And here is my overall review regarding your mid-term project checkpoint! 

- Functionality
I can upload data to AWS S3 bucket using your s3.py
Proper logging messages over all files
The create_db works fine and the structure of database is correct

- Readability and code quality
The names for variables are meaningful and easy to understand
There is no very long or confusing function. All functions are short and clear. 

- Overall design
Codes are modular and extensible
All user arguments are listed on run.py file, and users are able to run just one script for all the functionalities.
Functions are placed at the proper locations/scripts
Successfully passed the tests over test/test_s3.py

- Documentation
The guidelines on README.MD are pretty clear and easy to follow with. 
Love the idea that you placed a screen sheet of Trump's tweet on the top of README.MD
The docstrings clearly explain what each function does

**Comment by ydDianYu** [comment]
The above commits:
- Removed the redundant Dockerfile(s) in the `app` folder;
- Changed double-quotes to single-quotes;
- Added back the `TweetManager` class and `add_tweet()` functionality in the `add_tweets.py` script.

Thanks again for your detailed review!

**Pull request merged**
